[project]
name = "tiny-kite-mcp-client"
version = "0.1.0"
description = "A tiny kite mcp client"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=3.4.3",
    "browser-cookie3>=0.20.1",
    "fastmcp>=2.5.1",
]
